{{- if .Values.istio.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "profile-service.fullname" . }}-authz
  labels:
    {{- include "profile-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "profile-service.fullname" . }}
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/*/sa/*"
{{- end }}
