apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: booking-service
  namespace: booking-service
spec:
  interval: 5m
  chart:
    spec:
      chart: ./services/booking-service/deployments
      sourceRef:
        kind: GitRepository
        name: backend-gitops
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/viethung213/booking-service
      tag: latest # {"$imagepolicy": "flux-system:booking-service-policy"}

