{{- if and .Values.grpcRoute.enabled .Values.grpcRoute.parentRefs }}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "dispute-service.fullname" . }}-grpcroute
  labels:
    {{- include "dispute-service.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.grpcRoute.parentRefs | nindent 4 }}
  {{- if .Values.grpcRoute.hosts }}
  hostnames:
  {{- range .Values.grpcRoute.hosts }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
    - matches:
      {{- range .Values.grpcRoute.services }}
        - method:
            service: {{ . | quote }}
      {{- end }}
      backendRefs:
        - name: {{ include "dispute-service.fullname" $ }}
          port: {{ $.Values.service.ports.grpc }}
{{- end }}
