apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - global-gateway-config.yaml
  - postgres-namespace.yaml
  - minio-namespace.yaml

helmCharts:
  - name: kafka
    repo: https://charts.bitnami.com/bitnami
    version: 31.3.0
    releaseName: kafka
    namespace: kafka
    valuesFile: kafka-values.dev.yaml
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 15.5.4
    releaseName: postgres
    namespace: postgres
    valuesFile: postgres-values.dev.yaml
  - name: minio
    repo: https://charts.min.io/
    version: 5.4.0
    releaseName: minio
    namespace: minio
    valuesFile: minio-values.dev.yaml

patches:
  - target:
      name: minio.*
    patch: |-
      - op: add
        path: /metadata/namespace
        value: minio
  - target:
      name: export-minio.*
    patch: |-
      - op: add
        path: /metadata/namespace
        value: minio
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: global-gateway
      namespace: istio-ingress
    patch: |-
      apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: global-gateway
        namespace: istio-ingress
      spec:
        infrastructure:
          parametersRef:
            group: ""
            kind: ConfigMap
            name: global-gateway-config
