apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: kafka
    repo: https://charts.bitnami.com/bitnami
    version: 31.3.0
    releaseName: kafka
    namespace: kafka
    valuesFile: kafka-values.dev.yaml
