global:
  postgresql:
    auth:
      username: postgres
      password: mysecretpassword
      database: shared_dev_db

image:
  registry: docker.io
  repository: bitnamilegacy/postgresql

primary:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 2Gi

  networkPolicy:
    enabled: true
    extraIngress:
      # Allow Istio Ambient ztunnel HBONE traffic
      - ports:
          - port: 15008
            protocol: TCP
