{{- if and (not .Values.existingSecret) .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "profile-service.fullname" . }}-secrets
  labels:
    {{- include "profile-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
