resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

config:
  RUST_LOG: "info,interaction_service=info"

hpa:
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

externalSecrets:
  enabled: true
  vaultPath: interaction-service
