apiVersion: v1
kind: ConfigMap
metadata:
  name: dispute-service-config
  labels:
    app: dispute-service
data:
  SERVER_PORT: "8080"
  GRPC_PORT: "50051"
  KAFKA_BROKERS: "kafka.default.svc.cluster.local:9092"
