apiVersion: v1
kind: Secret
metadata:
  name: dispute-service-secret
  labels:
    app: dispute-service
type: Opaque
stringData:
  DB_HOST: "postgres.default.svc.cluster.local"
  # Add other sensitive credentials like DB_USER, DB_PASSWORD here
