apiVersion: v1
kind: Namespace
metadata:
  name: booking-service
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    team: backend
    purpose: booking-management
    service: booking-service
