apiVersion: v1
kind: Namespace
metadata:
  name: dispute-service
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    team: backend
    purpose: dispute-resolution
    service: dispute-service
