apiVersion: v1
kind: Namespace
metadata:
  name: finance-service
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    team: backend
    purpose: finance-management
    service: finance-service
