apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kafka-namespace.yaml
  - kafka-service-mapping.yaml
  - global-gateway.yaml
  - root-health-route.yaml
  - root-httproute.yaml
  - booking-namespace.yaml
  - booking-waypoint.yaml
  - identity-namespace.yaml
  - identity-waypoint.yaml
  - interaction-namespace.yaml
  - interaction-waypoint.yaml
  - profile-namespace.yaml
  - profile-waypoint.yaml
  - dispute-namespace.yaml
  - dispute-waypoint.yaml
  - finance-namespace.yaml
  - finance-waypoint.yaml
  - notification-namespace.yaml
  - notification-waypoint.yaml


