apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kafka-namespace.yaml
  - kafka-service-mapping.yaml
  - global-gateway.yaml
  - booking-namespace.yaml
  - booking-waypoint.yaml
  - identity-namespace.yaml
  - identity-waypoint.yaml
  - interaction-namespace.yaml
  - interaction-waypoint.yaml
  - profile-namespace.yaml
  - profile-waypoint.yaml

