apiVersion: v1
kind: Namespace
metadata:
  name: notification-service
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    team: backend
    purpose: notification-delivery
    service: notification-service
