apiVersion: v1
kind: Namespace
metadata:
  name: profile-service
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    team: backend
    purpose: companion-profile-catalogue
    service: profile-service
