{{- if and (not .Values.existingSecret) .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}-secrets
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.secrets }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
