{{- if .Values.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "booking-service.fullname" . }}-authz
  labels:
    {{- include "booking-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "booking-service.fullname" . }}
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              {{- toYaml .Values.authorizationPolicy.principals | nindent 14 }}
{{- end }}
