{{- if and .Values.secrets (not .Values.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interaction-service.fullname" . }}-secrets
  labels:
    {{- include "interaction-service.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.secrets }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
